#!/usr/bin/env bash
set -euo pipefail

output_dir=${1:?usage: verify.sh <output-dir>}
inspect_dir=$output_dir/inspect
report_file=$output_dir/POLICY_AUTH_MODEL_SUMMARY.txt
status=0

: >"$report_file"

pass() {
    printf '[PASS] %s\n' "$1" | tee -a "$report_file"
}

fail() {
    printf '[FAIL] %s\n' "$1" | tee -a "$report_file" >&2
    status=1
}

expect_group() {
    local group_name=$1
    if grep -q "^${group_name}:" "$inspect_dir/group"; then
        pass "group ${group_name} present"
    else
        fail "group ${group_name} missing"
    fi
}

check_pam_materialized() {
    local pam_name=$1
    local inspect_pam=$inspect_dir/$pam_name
    local inspect_authselect=$inspect_dir/authselect-$pam_name

    if [[ -s "$inspect_pam" ]]; then
        pass "$pam_name materialized"
    elif [[ -s "$inspect_authselect" ]]; then
        pass "$pam_name materialized via /etc/authselect"
    else
        fail "$pam_name missing"
    fi
}

if [[ ! -f "$inspect_dir/passwd" ]]; then
    fail "inspect/passwd missing"
    exit 1
fi

if [[ ! -f "$inspect_dir/group" ]]; then
    fail "inspect/group missing"
    exit 1
fi

root_line=$(grep '^root:' "$inspect_dir/passwd" || true)
openruyi_line=$(grep '^openruyi:' "$inspect_dir/passwd" || true)

if [[ "$root_line" == *":/bin/bash" ]]; then
    pass "root shell is /bin/bash"
else
    fail "root shell mismatch: ${root_line:-missing}"
fi

if [[ -n "$openruyi_line" ]]; then
    IFS=: read -r _ _ openruyi_uid _ _ openruyi_home openruyi_shell <<<"$openruyi_line"
    if [[ "$openruyi_uid" != 0 ]]; then
        pass "openruyi uid is non-root"
    else
        fail "openruyi uid is root"
    fi
    if [[ "$openruyi_home" == "/home/openruyi" ]]; then
        pass "openruyi home is /home/openruyi"
    else
        fail "openruyi home mismatch: ${openruyi_home:-missing}"
    fi
    if [[ "$openruyi_shell" == "/bin/bash" ]]; then
        pass "openruyi shell is /bin/bash"
    else
        fail "openruyi shell mismatch: ${openruyi_shell:-missing}"
    fi
else
    fail "openruyi entry missing"
fi

if [[ -f "$inspect_dir/authselect-current-raw.rc" ]]; then
    authselect_rc=$(tr -d '\n' <"$inspect_dir/authselect-current-raw.rc")
    if [[ "$authselect_rc" == 0 ]]; then
        current_profile=$(tr -d '\n' <"$inspect_dir/authselect-current-raw.txt")
        if [[ "$current_profile" == openruyi-local* ]]; then
            pass "authselect current profile is $current_profile"
        else
            fail "authselect current profile mismatch: ${current_profile:-empty}"
        fi
    else
        fail "authselect inspection command failed with rc=$authselect_rc"
    fi
else
    fail "authselect inspection rc missing"
fi

for pam_name in authselect-system-auth authselect-password-auth; do
    pam_file=$inspect_dir/$pam_name
    if [[ -s "$pam_file" ]]; then
        if grep -q '^# Generated by authselect' "$pam_file"; then
            pass "$pam_name generated by authselect"
        else
            fail "$pam_name content mismatch"
        fi
    else
        fail "$pam_name missing"
    fi
done

for pam_name in system-auth password-auth; do
    check_pam_materialized "$pam_name"
done

expect_group adm
expect_group wheel
expect_group users

if [[ $status -eq 0 ]]; then
    printf 'Policy auth-model verification passed: %s\n' "$output_dir" | tee -a "$report_file"
else
    printf 'Policy auth-model verification failed: %s\n' "$output_dir" | tee -a "$report_file" >&2
fi

exit "$status"
