# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: Zheng Junjie <zhengjunjie@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

name: update package to obs

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
     - 'SPECS/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  queue: max
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Install tools
      uses: ./.github/actions/setup-obs-tools
    - name: Setup osc config
      env:
        OSC_PASSWORD: ${{ secrets.BOT }}
      run: |
        set -euo pipefail
        install -d -m 700 ~/.config/osc
        cat > ~/.config/osc/oscrc <<EOF
        [general]
        apiurl = https://build.openruyi.cn
        [https://build.openruyi.cn]
        pass = ${OSC_PASSWORD}
        user = a-bot
        credentials_mgr_class=osc.credentials.PlaintextConfigFileCredentialsManager
        EOF
        chmod 600 ~/.config/osc/oscrc
    - name: run script
      run: |
        set -euo pipefail
        ./scripts/update-package "${{ github.event.before }}" "${{ github.sha }}"
